# -*- coding: utf-8 -*-
"""ESTR2020

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HSCSkbd22B1mpUj8W3m2zkTHjeITscvD
"""

import pandas as pd
import numpy as np
from scipy.stats import norm
from scipy.stats import gamma
from scipy.stats import loggamma

def load_data():
    df = pd.read_csv("./DataSet4STAT/regression.csv")

    X = df.iloc[:,:-1].values
    y = df.iloc[:,-1].values
    return X, y

X, y = load_data()

def unnormalized_full_log_posterior(X, y, U, beta):
  p = np.matmul(X, U) * beta * np.sum(U)
  p = 1 / (1 + np.exp(-p))

  #as p range from [0, 1], we need to control p not strictly equal to 0 or 1,
  #else it cause nan doing log(0)
  epsilon = 1e-15
  p = np.clip(p, epsilon, 1 - epsilon)

  #calculate full log posterior by sum of log priors and loglikelihood
  log_lik = np.dot(y, np.log(p)) + np.dot((1 - y), np.log(1 - p))
  log_prior_beta = np.log(beta) - 2 * beta
  log_prior_U = -np.sum(np.abs(U))
  full_log_post = log_lik + log_prior_beta + log_prior_U
  return full_log_post

def MH_1step_U(X, y, U_old, beta, i, step):
  U_proposal = np.copy(U_old)
  U_proposal[i] = norm.rvs(loc=U[i], scale=step, size=1)

  log_acceptance = unnormalized_full_log_posterior(X, y, U_proposal, beta) \
            - unnormalized_full_log_posterior(X, y. U_old, beta)

  if np.log(np.random.uniform(0, 1)) < log_acceptance:
    return U_proposal, 1
  else:
    return U_old, 0

def MH_1step_beta(X, y, U, beta_old, step):
  b = beta_old / (step * step)
  a = beta_old * b
  beta_proposal = gamma.rvs(c = a, scale = 1 / b)
  b_new = beta_proposal / (step * step)
  a_new = beta_proposal * b_new

  #log of ratio of posterior densities
  log_p = unnormalized_full_log_posterior(X, y ,U, beta_proposal) \
            - unnormalized_full_log_posterior(X, y, U, beta_old)

  #log of ratio of gamma proposal densities
  log_q = gamma.logpdf(beta_old, a = a_new, scale = (1 / b_new)) \
        - gamma.logpdf(beta_proposal, a = a, scale = (1 / b))
  log_acceptance = log_p + log_q

  acceptance = np.exp(min(0, log_acceptance))
  if np.log(np.random.uniform(0, 1)) < log_acceptance:
    return beta_proposal, 1
  else:
    return beta_old, 0

def MH_within_Gibbs(X, y, J, steps):
  U = np.full((J+1, 100), np.nan)
  beta = np.full((J+1,1), np.nan)

U = np.array(norm.rvs(loc=0, scale=1, size=100))
beta = gamma.rvs(1, 1, 1)