# -*- coding: utf-8 -*-
"""ESTR2020

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HSCSkbd22B1mpUj8W3m2zkTHjeITscvD
"""

import pandas as pd
import numpy as np
import arviz as az
from scipy.stats import norm
from scipy.stats import gamma
from scipy.stats import loggamma
from scipy.special import log_expit
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf

def load_data():
    df = pd.read_csv("./regression.csv")

    X = df.iloc[:,:-1].values
    y = df.iloc[:,-1].values
    return X, y

X, y = load_data()

def unnormalized_full_log_posterior(X, y, U, beta):
  bias_term = np.matmul(X, U) * beta * np.sum(U)
  # --- Numerically Stable Sigmoid ---
  # For positive inputs: 1 / (1 + exp(-x)) -> No overflow risk
  # For negative inputs: exp(x) / (1 + exp(x)) -> No overflow risk
  p = log_expit(bias_term)

  #as p range from [0, 1], we need to control p not strictly equal to 0 or 1,
  #else it cause nan doing log(0)
  epsilon = 1e-15
  p = np.clip(p, epsilon, 1 - epsilon)

  #calculate full log posterior by sum of log priors and loglikelihood
  log_lik = np.dot(y, np.log(p)) + np.dot((1 - y), np.log(1 - p))
  log_prior_beta = np.log(beta) - 2 * beta
  log_prior_U = -np.sum(np.abs(U))
  full_log_post = log_lik + log_prior_beta + log_prior_U
  return full_log_post

def MH_1step_U(X, y, U_old, beta, i, step):
  U_proposal = np.copy(U_old)
  U_proposal[i] = norm.rvs(loc=U_old[i], scale=step)

  log_acceptance = unnormalized_full_log_posterior(X, y, U_proposal, beta) \
            - unnormalized_full_log_posterior(X, y, U_old, beta)

  if np.log(np.random.uniform(0, 1)) < log_acceptance:
    return U_proposal, 1
  else:
    return U_old, 0

def MH_1step_beta(X, y, U, beta_old, step):
  epsilon = 1e-10

  b = max(beta_old / (step * step), epsilon)
  a = max(beta_old * b, epsilon)
  beta_proposal = gamma.rvs(a = a, scale = 1 / b)
  b_new = beta_proposal / (step * step)
  a_new = beta_proposal * b_new

  #log of ratio of posterior densities
  log_p = unnormalized_full_log_posterior(X, y ,U, beta_proposal) \
            - unnormalized_full_log_posterior(X, y, U, beta_old)

  #log of ratio of gamma proposal densities
  log_q = gamma.logpdf(beta_old, a = a_new, scale = (1 / b_new)) \
        - gamma.logpdf(beta_proposal, a = a, scale = (1 / b))
  log_acceptance = log_p + log_q

  acceptance = np.exp(min(0, log_acceptance))
  if np.log(np.random.uniform(0, 1)) < log_acceptance:
    return beta_proposal, 1
  else:
    return beta_old, 0

def MH_within_Gibbs(X, y, J, steps):
  U = np.full((J+1, 100), np.nan)
  beta = np.full(J+1, np.nan)
  U[0,:] = np.array(norm.rvs(loc=0, scale=3, size=100))
  beta[0] = gamma.rvs(a = 1, scale = 1)

  beta[0] = 5
  u_accept = 0
  beta_accept = 0
  for j in range(1, (J+1)):
    U_temp = np.copy(U[j-1,:])
    for i in range(100):
      U_temp, temp = MH_1step_U(X, y, U_temp, beta[j-1], i, steps[0])
      u_accept += temp
    U[j,:] = U_temp
    beta[j], temp = MH_1step_beta(X, y, U_temp, beta[j-1], steps[1])
    beta_accept += temp
    if j % 1000 == 0:
      print(f"Iteration {j}/{J} completed.")
  print(f"U Acceptance Rate: {u_accept / (J * 100):.2%}")
  print(f"Beta Acceptance Rate: {beta_accept / J:.2%}")
  return U, beta

U_sample, beta_sample = MH_within_Gibbs(X, y, 5000, [1.2,1])

#Burn-in first 50% samples:
U_burnt = U_sample[-(5000//2):]
beta_burnt = beta_sample[-(5000//2):]

# Plot Trace Plot

plt.figure(figsize=(12, 4))
plt.plot(beta_burnt, color='blue', linewidth=1)
plt.title("Trace Plot of Variable", fontsize=14)
plt.xlabel("Time Index")
plt.ylabel("Value")
plt.grid(True)
plt.tight_layout()
plt.show()

# Plot ACF
plt.figure(figsize=(8, 6))
plot_acf(beta_burnt, lags=30, alpha=0.05)  # alpha=0.05 adds confidence intervals
plt.title("Autocorrelation Function (ACF)", fontsize=14)
plt.tight_layout()
plt.show()

# Plot Trace Plot

plt.figure(figsize=(12, 4))
plt.plot(U_burnt[:,22], color='blue', linewidth=1)
plt.title("Trace Plot of Variable", fontsize=14)
plt.xlabel("Time Index")
plt.ylabel("Value")
plt.grid(True)
plt.tight_layout()
plt.show()

# Plot ACF
plt.figure(figsize=(8, 6))
plot_acf(U_burnt[:,22], lags=30, alpha=0.05)  # alpha=0.05 adds confidence intervals
plt.title("Autocorrelation Function (ACF)", fontsize=14)
plt.tight_layout()
plt.show()